services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: alytics-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - alytics-network

  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
      - 5672
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 15s
      retries: 3
    networks:
      - alytics-network

  phpfpm:
    build: .
    container_name: phpfpm
    volumes:
      - "./app:/app"
    command: bash -c "chmod -R 777 /app/frontend/runtime && cd /app && (yes | php yii migrate/up) && php-fpm"
    depends_on:
      #- postgres
      rabbitmq:
        condition: service_healthy
    networks:
      - alytics-network

  nginx:
    image: bitnami/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: local.host
      VIRTUAL_PORT: 80
    volumes:
      - "./config/nginx/local.host.conf:/opt/bitnami/nginx/conf/server_blocks/local.host.conf:ro"
      - "./app:/app"
    depends_on:
      - phpfpm
    networks:
      - alytics-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "88:80"
    expose:
      - "88"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.ru"
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - alytics-network

  # development container
  # after development it can be deleted
  dev-container:
    image: php:latest
    container_name: dev-container
    command: /bin/bash
    tty: true
    volumes:
      - "./app:/app"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - alytics-network

networks:
  alytics-network:
    driver: bridge
